---
title: "Problem Set 6"
author: "Rebecca Xi"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(infer)
library(gt)
library(ggplot2)
library(tidyverse)
```

## Question 1: Sampling and Confidence Intervals

```{r 1, echo=FALSE}

# Here I write a function, create_deck(), which creates a deck of cards as a
# tibble with 52 rows and four columns: suit, value, points and name. (I list
# the value column first so as to mimic the table in the problem set
# instructions.) The cards are ordered by suit: diamonds, hearts, clubs, spades,
# and go from 2 to Ace within each suit. J, Q, K, and A each have a point value
# of 10, which I set using an ifelse() condition in creating the points column.
# The name column pastes the value and suit, separated by “of".

create_deck <- function() {
  tibble(
    value = rep(c(2:10, "J", "Q", "K", "A"), times = 4),
    points = ifelse(
      value == "J" | value == "K" | value == "Q" | value == "A", 
      10, 
      value
    ),
    suit = rep(c("diamonds", "hearts", "clubs", "spades"), each = 13),
    name = paste(value, suit, sep = " of ")
  )
}

# Here I write a draw_card() function which takes parameters n (how many cards
# to draw) and report (which column to return). First, the function calls
# create_deck() to set up the deck of cards, then calls sample_n() to sample n
# cards from the deck and selects the requested column. I end by calling pull()
# in order to convert the function output from a column to the desired format.

draw_card <- function(n, report) {
  create_deck() %>% 
  sample_n(size = n) %>%
  select(report) %>% 
  pull()
}
```


### 1A)

```{r 1A, echo=FALSE}

# I first set the seed to 2. I then call my draw_card function with n = 4 and
# report = “name”.

set.seed(2)
draw_card(n = 4, report = "name")
```


### 1B)

```{r 1B, echo=FALSE}

# Now I set the seed to 3. I create a tibble called “hands” that draws a sample
# (without replacement) of 5 cards, 100 times. I then use map_lgl to create a
# column called “face” which tests whether there are any face cards (J, Q, K) in
# the hand, using an ifelse() condition. (I am sure there are more efficient
# ways to test for at least one face card within a draw, but here I end up doing
# it manually by checking each index of the draw.)

set.seed(3)
hands <- tibble(
  draw = map(1:100, ~ draw_card(n = 5, report = "value")),
  face = map_lgl(
    draw, 
    ~ ifelse(
      .[[1]] %in% c("J", "Q", "K") |
      .[[2]] %in% c("J", "Q", "K") |
      .[[3]] %in% c("J", "Q", "K") |
      .[[4]] %in% c("J", "Q", "K") |
      .[[5]] %in% c("J", "Q", "K"), 
      TRUE, 
      FALSE)
  )
)

# Finally, I use gt() to display the first 5 rows of the tibble. I slice for the
# first five rows, and then use the gt package to add a title and subtitle and
# relabel the columns as appropriate.

fivecards <- hands %>% 
  slice(1:5) %>% 
  gt() %>% 
  tab_header(
    title = "Hands of Five Cards",
    subtitle = "Checking for Face Values"
  ) %>%
  cols_label(
    draw = "Draw",
    face = "Face Cards?"
  )
fivecards
```


### 1C)

```{r 1C, echo=FALSE}

# I first set the seed to 4. Here I draw my own sample of 12 cards from the deck
# created by create_deck() and select just the name and points columns. I
# decided to directly use sample_n() with size = 12 to draw this sample rather
# than use the function I created earlier, draw_sample, in order to allow for
# selecting and viewing multiple columns from the deck tibble.

set.seed(4)
twelve_cards_once <- create_deck() %>% 
  sample_n(size = 12) %>% 
  select(name, points)

# Here I use gt() to display a table of all 12 sampled cards with card name and
# point value. I chose not to pipe directly from the previous code chunk to gt()
# so that I can successfully draw from twelve_cards_once, as a data frame, in
# 1E) later on.

twelve_cards_table <- twelve_cards_once %>% 
  gt() %>% 
  tab_header(
    title = "Sample of 12 Cards"
  ) %>% 
  cols_label(
    name = "Card Name",
    points = "Point Value"
  )
twelve_cards_table
```


### 1D)

```{r 1D, echo=FALSE}

# I call create_deck() to create the entire deck of cards and then call mean()
# within summarize() to find the average number of points. I have to first
# convert the entries in the points column to numeric values, in order to be
# able to apply the mean() function.

r1D <- create_deck() %>%  
  summarize(mean(as.numeric(points)))
```

The mean number of points in our entire deck is `r r1D`.


### 1E)

```{r 1E, echo=FALSE}

# I first set the seed to 5. Here I conduct bootstrapped resampling on the hand
# of 12 cards created in 1C). In sampling 1000 times, I have to sample with
# replacement so as to not get back the same hand of 12 cards every single time.
# I chose not to store these resamples in a tibble using map(), since doing so
# was giving me complications later on when I tried to plot the tibble.

set.seed(5)
bootstrap <- twelve_cards_once %>% 
  rep_sample_n(size = 12, reps = 1000, replace = TRUE)

# Now I replicate the plot shown in the problem set instructions, which compares
# the original sample mean to the mean of the bootstrapped resamples. I use
# summarize() to calculate the mean of the bootstrapped samples, 

bootstrap_mean <- bootstrap %>% 
  group_by(replicate) %>% 
  select(replicate, name, points) %>% 
  summarize(bootstrap_mean = mean(as.numeric(points)))

#

bootstrap_mean_overall <- bootstrap_mean %>% 
  summarize(bootstrap_mean_overall = mean(bootstrap_mean))

# Here I plot the bootstrap_mean table on the x-axis. It took some playing
# around to settle on bins = 20, via a lot of help on Zoom.

bootstrap_plot <- bootstrap_mean %>% 
  ggplot(aes(x = bootstrap_mean)) +
  geom_histogram(bins = 20) +
  labs(
    title = "Distribution of 1000 Bootstrapped Resamples",
    subtitle = "From original 12 card sample with mean 7.231",
    x = "Points",
    y = "Samples"
  ) +
  geom_vline(
    xintercept = bootstrap_mean_overall$bootstrap_mean_overall, 
    color = "lightblue"
  ) +
  geom_text(
    aes(
      x = 7.1, 
      label="Mean of Bootstrapped Samples", 
      y = 51), 
    color = "lightblue",
    angle = 90
  ) +
  theme_classic()
bootstrap_plot
```

In one sentence, tell us why the mean of the bootstrapped resamples isn’t 
exactly the same as the mean of the original sample. 



### 1F)

```{r 1F, echo=FALSE}

# Using your bootstrapped sampling distribution, create “percentile confidence
# intervals” at the 80%, 90%, 95%, and 99% confidence levels. If you need a
# refresher, check out PPBDS 10.2.1. Make a gt table with two columns; one for
# the level and one for the interval. Include the sample mean (the
# (non-bootstrapped) mean points for your sample) as a “source note” at the
# bottom of your table.



```


### 1G)

```{r 1G, echo=FALSE}

# Set the seed to 2. Print a call to your draw_card function, where n = 4 and
# report = “name”.


```



## Question 2: Shiny

[link to Shiny app]


